Issue: 91; Support multi-lines text in table cells with write_html #91
PyFPDF/fpdf2 pull request #211
Opened 2021-08-29 19:52 UTC by divyaman777

### **Table Data Tuple** 
`data = (`
    &emsp;`("First name ", "Last name ", "Age", "City"),`
    &emsp;`("Chandrapratap singh \ntomer rajput ", "Smith this can \nalso see this err \nokay", "34", "San Juan"),`
    &emsp;`("Mary \nthis is the \ncorrection", "Ramos \n also this \n over laping data \nto se the error ", "45", "Orlando"),`
    &emsp;`("Carlson data \ncan be multiline ", "Banks", "19 \n32", "Los Angeles \nthis to"),`
    &emsp;`("Lucas \nnot working ", "Cimon \nsame to see the \nerror in prev", "31", "Saint-Mahturin-sur-Loire \nthis also"),`
`)`

![image](https://user-images.githubusercontent.com/54167912/131262939-fe0711d2-7ee5-4998-9c1e-a5cd8a722cbd.png)
### **                                        fig 1: table before adding multi-line text support.**

![image](https://user-images.githubusercontent.com/54167912/131262822-af85bf5b-330c-4033-8686-02439b267b13.png)
### **                                       fig 2: table after adding multi-line text support.**

firstly I replaced the \n(in data) by <br> tag
`        text = text.replace("\n", "<br>") `
then I get the coordinates of the table 

` self.top_position_x = self.pdf.x if(self.top_position_x == -1) else self.top_position_x`
`  self.top_position_y = self.pdf.y if(self.top_position_y == -1) else self.top_position_y`

and created a function to make vertical lines using above coordinates 
`def output_table_sep_vertical(self, width):`
 &emsp; `y1 = self.pdf.y`
&emsp; `self.pdf.line(self.top_position_x+width, self.top_position_y, self.top_position_x+width, y1)`

Now this function will be called equal to the number of columns in the table.

`width = 0`
`for i in self.table_col_width:`
&emsp; `self.output_table_sep_vertical(width)`
&emsp; `width += self.width2unit(i)`
`self.output_table_sep_vertical(width)`

2021-08-30 06:44 UTC, Lucas-C commented
Hi @divyaman777!

Thanks for contributing a PR, and welcome 😉

I added a commit to format the code with [black](https://github.com/psf/black),
in order for the tests suite to get executed after the initial linter checks.

It seems that your code change is breaking several non regression tests:
https://github.com/PyFPDF/fpdf2/runs/3458916240
```
=========================== short test summary info ============================
FAILED test/html/test_html.py::test_html_simple_table - AssertionError: asser...
FAILED test/html/test_html.py::test_html_table_line_separators - AssertionErr...
FAILED test/html/test_html.py::test_html_table_th_inside_tr_issue_137 - Asser...
FAILED test/html/test_html.py::test_html_table_with_border - AssertionError: ...
FAILED test/html/test_html.py::test_html_bold_italic_underline - AssertionErr...
FAILED test/html/test_html.py::test_customize_ul - AssertionError: assert [b'...
FAILED test/html/test_html.py::test_img_inside_html_table - AssertionError: a...
FAILED test/html/test_html.py::test_img_inside_html_table_without_explicit_dimensions
FAILED test/html/test_html.py::test_img_inside_html_table_centered - Assertio...
FAILED test/html/test_html.py::test_img_inside_html_table_centered_with_align
FAILED test/html/test_html.py::test_img_inside_html_table_centered_with_caption
FAILED test/outline/test_outline_html.py::test_html_toc - AssertionError: ass...
FAILED test/outline/test_outline_html.py::test_html_toc_2_pages - AssertionEr...
================= 13 failed, 179 passed, 11 warnings in 37.08s =================
```

If you want to pursue work on this feature,
I invite you to run the tests in your development environment,
in order to understand why they failed following your changes.

Also, feel free to ask any question on how contributing works here!

2021-08-30 06:46 UTC, Lucas-C requested changes
Code review status: requesting changes in order for tests to pass.

2021-09-28 15:24 UTC, Lucas-C commented
@divyaman777 do you plan to continue your work here?

No worries if the answer is "no", I'd just like to know the status of this PR 😉

2021-11-12 02:26 UTC, divyaman777 commented
> 
> 
> Hi @divyaman777
> 
> Without further news from you, I will probably close this PR soon
> 
> Regards

I am not able to understand the test cases you have put, this code is running fine on my lock machine if you could help me with test case thing then I will proceed .

2021-11-12 21:18 UTC, Lucas-C commented
`fpdf2` documentation describes how to run the unit tests on your computer:
https://pyfpdf.github.io/fpdf2/Development.html#testing

The tests ensure that no code change significantly modifies the behaviour of the library.
Currently, your code change "breaks" 13 tests.
This means that if this PR is merged, many users would be surprised by the new behaviour of `write_html()` as it would not generate the exact same PDFs as before.

Contributing a code patch is very nice, but you will need to take the time to understand how & why `write_html()` method behaviour changed if you want to see your PR merged.
If not, that's perfectly fine !
I'll simply close this PR.
Other people could still submit another PR to fix #91, based on your code or another approach.

2022-02-07 09:44 UTC, Lucas-C commented
Hi @divyaman777

FYI, given this PR hasn't seen any activity over the past 3 months, I may consider closing it.

2022-02-24 15:50 UTC, closed without merging