Manage a stack of local graphic state
PyFPDF/fpdf2 pull request #290
Opened 2021-10-31 23:34 UTC by gmischler

as of #250 (second part).

* New ability to change graphics state settings temporarily.
* New context manager .local_context() to create a temporary state environment.
* Rotations don't conflict with graphics state settings anymore.
* Templates don't need to jump through hoops anymore to rotate stuff.

2021-11-09 16:04 UTC, Lucas-C requested changes
Good job overall @gmischler !

I made a few comments on your PR

2021-11-09 16:04 UTC, Lucas-C commented on fpdf/graphics_state.py
> +                dash_pattern="[] 0 d",
Note `line_width`?

2021-11-09 16:04 UTC, Lucas-C commented on fpdf/graphics_state.py
> +    @draw_color.setter
Il faut que les "setters" de la classe parente fassent désormais appel à ces méthodes : `FPDF.set_stretching`, `FPDF.set_draw_color`, `FPDF.set_fill_color`, `FPDF.set_text_color`, `FPDF.set_line_width`, `FPDF.set_dash_pattern`, `FPDF.set_font`, `FPDF.set_font_size`

2021-11-09 16:04 UTC, Lucas-C commented on test/template/test_flextemplate.py
> -            "x2": 70,
Why changing those values?
It'b better if the exeact same PDF file could is generated BEFORE & AFTER this PR, to ensure backward-compatibility

2021-11-10 17:29 UTC, gmischler commented on CHANGELOG.md
> -Changelog
Looks like it. My local file is formatted exactly as the the other's, though...

2021-11-12 15:11 UTC, Lucas-C commented on fpdf/fpdf.py
> +        GraphicsStateMixin.__init__(self)
> there's no way around naming them individually
I'm not so sure. Actually, this works pretty well:
```python
class AMixin:
    def __init__(self):
        super().__init__()
        print("AMixin.__init__")

class BMixin:
    def __init__(self):
        super().__init__()
        print("BMixin.__init__")

class FPDF(AMixin, BMixin):
    def __init__(self):
        super().__init__()
        print("FPDF.__init__")

class MyPDF(FPDF):
    pass

print(MyPDF())
```

2021-11-12 15:12 UTC, Lucas-C commented on fpdf/graphics_state.py
> +        self.__statestack = [
Alright

2021-11-12 15:14 UTC, Lucas-C commented on fpdf/graphics_state.py
> +    @draw_color.setter
(sorry for the sudden mix of French in the review, my mistake)

2021-11-12 15:15 UTC, Lucas-C commented on test/template/test_flextemplate.py
> -            "x2": 70,
Ok then, good job

2021-11-12 15:19 UTC, Lucas-C commented on fpdf/fpdf.py
>          self.draw_color = "0 G"
Alright, I understand now.

Could you please extend your "graphics state variables from the stack" comment here, in `FPDF.__init__`,
to make explicit that we are **not** initializing properties at this point,
but setting default values of properties defined in `GraphicsStateMixin`?

2021-11-12 15:19 UTC, Lucas-C commented on fpdf/graphics_state.py
> +    @draw_color.setter
Ok, I see now why this is not needed

2021-11-12 18:00 UTC, gmischler commented on fpdf/fpdf.py
> +        GraphicsStateMixin.__init__(self)
So you're saying I had the wrong sequence in my head all those years?
Go figure...

(I used to write tons of code for Python 1.5, so I'll use that as my excuse... :wink:)

2021-11-12 18:11 UTC, gmischler commented on fpdf/fpdf.py
>          self.draw_color = "0 G"
We don't seem to think of the same operation when saying "initializing properties".
I'll find a phrasing that makes it clear what happens either way.

2021-11-12 21:30 UTC, Lucas-C commented on fpdf/fpdf.py
>          self.draw_color = "0 G"
That's perfect, thank you!

2021-11-12 21:30 UTC, Lucas-C approved these changes

2021-11-12 21:30 UTC, merged

2021-11-12 21:31 UTC, Lucas-C commented
Thank you @gmischler for this great code refactoring!

2021-11-19 13:52 UTC, Lucas-C commented
FYI I mentioned you in this blog article 😉
https://chezsoi.org/lucas/blog/hacktoberfest-on-fpdf2.html