Migrate tests to pytest
PyFPDF/fpdf2 pull request #80
Opened 2021-01-20 22:38 UTC by eumiro

This is a longer branch with incremental migration of tests to pytest.

1. Prepare the infrastructure to use `tests/` as the test directory
2. Migrate the `test_barcodes` test module together with heavily edited `utilities.py` file (and remove the `test/barcodes` directory)

Please, share your ideas/questions/improvements in the discussion here.

It is a draft PR to avoid accidental merge. New commits will appear here later.

2021-01-20 22:43 UTC, eumiro commented
Please ignore the `codecov` reports for now. The first commit in this PR deactivates all existing tests and runs only those migrated within this branch.

2021-01-21 08:35 UTC, Lucas-C requested changes

2021-01-21 08:35 UTC, Lucas-C commented on tox.ini
> +deps =
Please use `test/requirements.txt` here to avoid duplicating dependencies

2021-01-21 08:47 UTC, Lucas-C commented
Thanks for starting this work.

First off: do you plan to migrate all tests to `pytest` in a single PR or not?

Depending on the answer to this question, my comments below may be inaccurate.

Overall, I'm not really a big fan of the global strategy to migrate to a 2nd directory named `tests`, for several reasons:
- I don't really see the benefit of it: why migrating tests one by one? Given the goal here, the tests logic should not vary in this effort, only the "glue" around executing them.
- it is very important that the tests continue to pass in the `GitHub Actions` pipeline during this effort,
and they are already launched by `pytest`: https://github.com/PyFPDF/fpdf2/blob/master/.github/workflows/continuous-integration-workflow.yml#L39
- having a separate directory makes PRs difficult to read: many files are just moved around "as is", and moved files can be considered removed & recreated by `git` instead of just altered

Hence, my suggestion would be to incrementally add usage of `pytest` features without changing the files structures:
- renaming all test files with a `test_` prefix to be more standard and get rid of [this custom configuration entry](https://github.com/PyFPDF/fpdf2/blob/master/setup.cfg#L18)
- moving from classes to individual test functions
- introducing the use of `tmp_path`
- etc.

2021-01-21 09:09 UTC, eumiro commented
@Lucas-C since I am relatively new to this test suite, I first wanted to go class by class in order to see working results fast. Already in the first tiny `test_barcodes` I could refactor the `assert_pdf_equal` and related methods. But now after two migrated modules I see the structure and I could do it the way you want to have it, i.e. one systemic change on the whole test suite at a time per PR with everything working in between.

2021-01-21 10:06 UTC, Lucas-C commented
Sounds good 😉

I understand your initial approach, not knowing much about the existing tests.

I already merged https://github.com/PyFPDF/fpdf2/pull/81 you just submitted: thanks!

Feel free to close or rebase this PR to continue.

And if there are tests that prove difficult to adapt to `pytest`, do not hesitate to ask for help or ideas on how to deal with them 
😊

2021-01-21 16:20 UTC, eumiro commented
This PR can be closed. Please follow #82

2021-01-21 16:20 UTC, closed without merging